### ISSUE TITLE
Error when running with config file

### ISSUE THREAD

**Issue by prusnak** [chill117/lnurl-node#34]
Steps to reproduce:

1. install lnurl locally `npm install lnurl` (without `-g`)
2. create config file as per documentation
3. run `./node_modules/.bin/lnurl server --configFile ./config.json`
4. observe the following error:

```
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1148:7)
    at Server.prepareStore (/home/bitcoin/node_modules/lnurl/lib/Server.js:580:25)
    at new Server (/home/bitcoin/node_modules/lnurl/lib/Server.js:34:20)
    at Object.createServer (/home/bitcoin/node_modules/lnurl/index.js:7:10)
    at Command.<anonymous> (/home/bitcoin/node_modules/lnurl/cli.js:269:9)
    at Command.listener [as _actionHandler] (/home/bitcoin/node_modules/commander/lib/command.js:466:17)
    at /home/bitcoin/node_modules/commander/lib/command.js:1170:65
    at Command._chainOrCall (/home/bitcoin/node_modules/commander/lib/command.js:1088:12)
    at Command._parseCommand (/home/bitcoin/node_modules/commander/lib/command.js:1170:27) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Oddly enough, this works when I specify options from config file manually on the command line. 🤷 

I am using NodeJS 14.x

**Comment by prusnak** [comment]
Edit: it seems I observe the same error even when I install lnurl globally (`npm i -g`)

**Comment by chill117** [comment]
It looks like your config.json is missing `"store"`. It might not be so intuitive, but the store and lightning configurations are defined as objects in the config.json file. For example:
```json
{
	"host": "localhost",
	"port": 3000,
	"url": "http://localhost:3000",
	"endpoint": "/lnurl",
	"auth": {
		"apiKeys": []
	},
	"lightning": {
		"backend": "lnd",
		"config": {}
	},
	"store": {
		"backend": "memory",
		"config": {}
	}
}
```

**Comment by prusnak** [comment]
You are correct. It was indeed missing `store`.

I got confused, because when passing arguments via command-line, the `lnurl` command correctly uses default values for `store`. So I assumed it is not mandatory to add this to the config json file.

**Comment by chill117** [comment]
I think it's a reasonable expectation that the defaults should be used when providing a config file. I'll mark that as a bug and fix it when I have a bit of time. Thanks for bringing it to my attention.

**Comment by chill117** [comment]
Fixed and will be in the next release.
